// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

/**
 * Actions that can be performed.
 * Purely aesthetic; have no actual effect on simulation.
 * (Although the simulation may want to track the 'parents' of
 * particular robots.)
 * Actions may have 'targets', which are the units on which
 * the actions were performed.
 */
public final class Action {
  private Action() { }
  public static final byte ATTACK = 0;
  public static final byte SPAWN_UNIT = 1;
  public static final byte MINE = 2;
  public static final byte BUILD = 3;
  public static final byte CONVERT_GOLD = 4;
  public static final byte TRANSFORM = 5;
  public static final byte UPGRADE = 6;
  public static final byte REPAIR = 7;
  public static final byte CHANGE_HP = 8;
  public static final byte FULLY_REPAIRED = 9;
  public static final byte LOCAL_ABYSS = 10;
  public static final byte LOCAL_FURY = 11;
  public static final byte LOCAL_CHARGE = 12;
  /**
   * Dies due to an uncaught exception.
   * Target: none
   */
  public static final byte DIE_EXCEPTION = 13;

  public static final String[] names = { "ATTACK", "SPAWN_UNIT", "MINE", "BUILD", "CONVERT_GOLD", "TRANSFORM", "UPGRADE", "REPAIR", "CHANGE_HP", "FULLY_REPAIRED", "LOCAL_ABYSS", "LOCAL_FURY", "LOCAL_CHARGE", "DIE_EXCEPTION", };

  public static String name(int e) { return names[e]; }
}

